<a href="https://colab.research.google.com/github/Gail529/chess_ML/blob/main/Untitled19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [60]:
data=pd.read_csv('/content/games.csv')

In [65]:
print(data.shape)
data.head()

(20058, 413)

   rated  turns  ...  increment_code_90+5  increment_code_90+8
0      0     13  ...                    0                    0
1      1     16  ...                    0                    0
2      1     61  ...                    0                    0
3      1     61  ...                    0                    0
4      1     95  ...                    0                    0

[5 rows x 413 columns]

In [62]:
data.columns
del data['id']
del data['created_at']
del data['last_move_at']
del data['white_id']
del data['black_id']
del data['opening_name']
del data['opening_eco']
del data['moves']

In [63]:
data['rating_diff'] = data['white_rating']-data['black_rating']
data.columns

Index(['rated', 'turns', 'victory_status', 'winner', 'increment_code',
       'white_rating', 'black_rating', 'opening_ply', 'rating_diff'],
      dtype='object')

In [56]:
data.dtypes

rated               bool
turns              int64
victory_status    object
winner            object
increment_code    object
white_rating       int64
black_rating       int64
opening_eco       object
opening_ply        int64
rating_diff        int64
dtype: object

In [ ]:
data.describe()

              turns  white_rating  black_rating   opening_ply
count  20058.000000  20058.000000  20058.000000  20058.000000
mean      60.465999   1596.631868   1588.831987      4.816981
std       33.570585    291.253376    291.036126      2.797152
min        1.000000    784.000000    789.000000      1.000000
25%       37.000000   1398.000000   1391.000000      3.000000
50%       55.000000   1567.000000   1562.000000      4.000000
75%       79.000000   1793.000000   1784.000000      6.000000
max      349.000000   2700.000000   2723.000000     28.000000

In [44]:
#Scaling continous variables 
#standardisation
from sklearn import preprocessing 
cols=['turns','white_rating', 'black_rating', 'opening_ply']
cols_to_scale=data[cols]
Standardisation = preprocessing.StandardScaler()  
scaled_cols= Standardisation.fit_transform(cols_to_scale) 
print ("\nStandardised columns : \n", scaled_cols)

Standardised columns :
 [[-1.4139516  -0.33178766 -1.36698461  0.0654322 ]
 [-1.32458542 -0.94295461 -1.12645864 -0.29208323]
 [ 0.01590722 -0.34552175 -0.30523428 -0.64959865]
 ...
 [-0.75859964 -1.2966074  -1.04055651 -0.64959865]
 [ 1.44576604 -0.81248077 -1.24328554 -0.29208323]
 [ 0.52231555 -1.24167104 -0.858444   -0.64959865]]

In [45]:
#Scaling continous variables 
#min max scaling
cols=['turns','white_rating', 'black_rating', 'opening_ply']
cols_to_scale=data[cols]
min_max_scaler = preprocessing.MinMaxScaler(feature_range =(0, 1)) 
scaled_cols = min_max_scaler.fit_transform(cols_to_scale) 
  
print ("\nAfter min max Scaling : \n", scaled_cols)

After min max Scaling :
 [[0.03448276 0.3736952  0.20785936 0.14814815]
 [0.04310345 0.28079332 0.24405377 0.11111111]
 [0.17241379 0.37160752 0.36763185 0.07407407]
 ...
 [0.09770115 0.22703549 0.25698035 0.07407407]
 [0.31034483 0.3006263  0.22647363 0.11111111]
 [0.22126437 0.23538622 0.28438469 0.07407407]]

In [64]:
# label encoding the data 
from sklearn.preprocessing import LabelEncoder 

categorical_feature_mask = data.dtypes==object
# filter categorical columns using mask and turn it into a list
categorical_cols = data.columns[categorical_feature_mask].tolist()

le = LabelEncoder() 
data['winner']= le.fit_transform(data['winner'])
data['rated']= le.fit_transform(data['rated'])


#categorical data

#import pandas as pd
data = pd.get_dummies(data, columns = categorical_cols)